Remove errant `,` that's causing compilation errors
```
Error: Module build failed (from ../../node_modules/@mdx-js/loader/index.js):
SyntaxError: unknown: Unexpected token (195:16)

  193 |   language='css'
  194 |   dark
> 195 |   format={false},
      |                 ^
  196 |   code={`
  197 |      .container {
  198 |        display: grid | inline-grid;
```