test: fix angular test error
fix this error log
```
Failed to collect coverage from /tmp/storybook/app/angular/src/builders/build-storybook/index.spec.ts
ERROR: /tmp/storybook/app/angular/src/builders/build-storybook/index.spec.ts: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
Invalid variable access: buildStandaloneMock
Allowed objects: Array, ArrayBuffer, Atomics, BigInt, BigInt64Array, BigUint64Array, Boolean, Buffer, DataView, Date, Error, EvalError, Float32Array, Float64Array, Function, GLOBAL, Generator, GeneratorFunction, Infinity, Int16Array, Int32Array, Int8Array, InternalError, Intl, JSON, Map, Math, NaN, Number, Object, Promise, Proxy, RangeError, ReferenceError, Reflect, RegExp, Set, SharedArrayBuffer, String, Symbol, SyntaxError, TextDecoder, TextEncoder, TypeError, URIError, URL, URLSearchParams, Uint16Array, Uint32Array, Uint8Array, Uint8ClampedArray, WeakMap, WeakSet, WebAssembly, arguments, clearImmediate, clearInterval, clearTimeout, console, decodeURI, decodeURIComponent, encodeURI, encodeURIComponent, escape, eval, expect, global, globalThis, isFinite, isNaN, jest, parseFloat, parseInt, process, queueMicrotask, require, root, setImmediate, setInterval, setTimeout, undefined, unescape.
Note: This is a precaution to guard against uninitialized mock variables. If it is ensured that the mock is required lazily, variable names prefixed with `mock` (case insensitive) are permitted.

   6 | const buildStandaloneMock = jest.fn().mockImplementation((_options: unknown) => Promise.resolve());
   7 |
>  8 | jest.mock('@storybook/angular/standalone', () => buildStandaloneMock);
```